#!/command/with-contenv bash

if [ "$WSDD_ENABLED" != "true" ]; then
    echo "WSDD is disabled. Exiting."
    exit 0
fi

if [ "$SAMBA_ENABLED" != "true" ]; then
    echo "WSDD requires Samba to be enabled. Skipping."
    exit 0
fi

echo "Starting WSDD..."
exec wsdd -v </dev/null
