#!/command/with-contenv /bin/bash
if [ "$WSDD_ENABLED" != "true" ] || [ "$SAMBA_ENABLED" != "true" ]; then
    echo "WSDD is disabled or Samba is missing. Exiting."
    exit 0
fi
echo "Starting WSDD..."
exec wsdd -v
