#!/command/with-contenv /bin/bash

/usr/local/bin/paperless-uploader.sh

# If in oneshot mode, the above script will exit 0.
# In that case, we trigger a halt for s6-overlay.
if [ "$API_UPLOADER_ONESHOT" = "true" ]; then
    echo "Oneshot mode: finished initial scan. Exiting container..."
    if [ -f /run/s6/basedir/bin/halt ]; then
        /run/s6/basedir/bin/halt
    else
        kill 1
    fi
fi
